FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

EXPOSE 8080
EXPOSE 8081

# Copy the project file and restore dependencies
COPY CustomEd.OtpService.csproj .
RUN dotnet restore

# Copy the remaining source code and build the application
COPY . .
RUN dotnet build -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Final stage for the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app

# Copy the published output from the build stage
COPY --from=publish /app/publish .

# Set the entry point for the container
ENTRYPOINT ["dotnet", "CustomEd.OtpService.dll"]